version: '3.9'

services:

  mongodb:
    container_name: 'mongo-db-meow-mingle'
    image: 'mongo:6.0'
    environment:
      MONGO_INITDB_DATABASE: meow-mingle-db
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'

  redis:
    container_name: 'redis-meow-mingle'
    image: 'redis:7.2.1'
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    ports:
      - '6379:6379'
    restart: on-failure
