server:
  port: 8080

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:meow-mingle}
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/meow-mingle-db?authSource=admin
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

subscription-task:
  thread-pool:
    thread-name-prefix: 'subscription-worker-'
    core-pool-size: 2
    max-pool-size: 4
  worker:
    timeout: 500
    key-name: 'subscription-events'

reaction-task:
  thread-pool:
    thread-name-prefix: 'reaction-worker-'
    core-pool-size: 2
    max-pool-size: 4
  worker:
    timeout: 500
    key-name: 'reaction-events'

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    ua.mevhen: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: '/logs/meow-mingle.log'
