server:
  port: 8080

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:meow-mingle}
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/meow-mingle-db?authSource=admin

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    ua.mevhen: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: '/logs/meow-mingle.log'
